---
description: 了解以下内容： "Catch" 不能出现在 "Try" 语句中的 "Finally" 之后
title: 在 "Try" 语句中，"Catch" 不能出现在 "Finally" 之后
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ec177fadf2490c3779e0ad3a1f754319e12bd9cc
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 02/14/2021
ms.locfileid: "100454945"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>在 "Try" 语句中，"Catch" 不能出现在 "Finally" 之后

`Catch` 语句出现在代码中结束 `Finally` 语句块的 `Try` 之后。 `Catch` 必须出现在 `Try...Catch...Finally` 语句块之内。  
  
 **错误 ID：** BC30379  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1. 将 `Catch` 语句移到代码中更合适的位置。  
  
## <a name="see-also"></a>另请参阅

- [Try...Catch...Finally 语句](../language-reference/statements/try-catch-finally-statement.md)
